name: AI Code Review

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout everything so git-diff works
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) (Optional) build your Next.js to surface errors
      - name: Setup Node & Install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      # 3) Java runtime
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 4) Prepare a folder for the remote JAR
      - name: Create libs directory
        run: mkdir -p ./libs

      # 5) Download your published SDK JAR
      - name: Download AI-CodeReview SDK JAR
        run: |
          wget -O ./libs/ai-code-autoreview-sdk-1.0.jar \
            https://github.com/Carson-NNY/MemoSphere/releases/download/V1/ai-code-autoreview-sdk-1.0-jar-with-dependencies.jar

      # 6) Capture Git metadata
      - name: Get repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get commit author
        run: echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      # 7) (Optional) Print for debugging
      - name: Print Git metadata
        run: |
          echo "Repo:   $REPO_NAME"
          echo "Branch: $BRANCH_NAME"
          echo "Author: $COMMIT_AUTHOR"
          echo "Message:$COMMIT_MESSAGE"

      # 8) Run the code-review CLI
      - name: Run AI code review
        env:
          OPENAI_API_KEY:              ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_HOST:             ${{ secrets.OPENAI_API_HOST }}
          ACCESS_TOKEN:                ${{ secrets.ACCESS_TOKEN }}
          SLACK_WEBHOOK_URL:           ${{ secrets.SLACK_WEBHOOK_URL }}
          AI_CODE_REVIEW_LOG_REPO_URI: ${{ secrets.AI_CODE_REVIEW_LOG_REPO_URI }}
          COMMIT_PROJECT:              ${{ env.REPO_NAME }}
          COMMIT_BRANCH:               ${{ env.BRANCH_NAME }}
          COMMIT_AUTHOR:               ${{ env.COMMIT_AUTHOR }}
          COMMIT_MESSAGE:              ${{ env.COMMIT_MESSAGE }}
        run: |
          # <-- note the “.” so it reviews the current repo
          java -jar ./libs/ai-code-autoreview-sdk-1.0.jar .
